CloudSense/CloudStack/Controllers/HomeController.cs
using CloudStack.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace CloudStack.Controllers
{
    public class HomeController : Controller
    {
        private DataAccess db = new DataAccess();

        public ActionResult Index()
        {
            HomeIndexViewModel model = null;

            if (ClaimsPrincipal.Current.Identity.IsAuthenticated)
            {
                model = new HomeIndexViewModel();
                model.UserSubscriptions = new Dictionary<string, Subscription>();
                model.UserCanManageAccessForSubscriptions = new List<string>();

                var subscriptions = AzureResourceManagerUtil.GetUserSubscriptions(ConfigurationManager.AppSettings["AADId"]);

                if (subscriptions != null)
                {
                    foreach (var subscription in subscriptions)
                    {

                        Subscription s = db.Subscriptions.Find(subscription.Id);
                        if (s != null)
                        {
                            subscription.IsConnected = true;
                            subscription.ConnectedOn = s.ConnectedOn;
                            subscription.ConnectedBy = s.ConnectedBy;
                            subscription.AzureAccessNeedsToBeRepaired = !AzureResourceManagerUtil.ServicePrincipalHasReadAccessToSubscription
                                (subscription.Id, ConfigurationManager.AppSettings["AADId"]);
                        }
                        else
                        {
                            subscription.IsConnected = false;
                        }

                        model.UserSubscriptions.Add(subscription.Id, subscription);
                        if (AzureResourceManagerUtil.UserCanManageAccessForSubscription(subscription.Id, ConfigurationManager.AppSettings["AADId"]))
                            model.UserCanManageAccessForSubscriptions.Add(subscription.Id);
                    }
                }
            }
            return View(model);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CloudSense/CloudStack/Controllers/SubscriptionController.cs
using CloudStack.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IdentityModel.Claims;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudStack.Controllers
{
    public class SubscriptionController : Controller
    {
        private DataAccess db = new DataAccess();

        public ActionResult Connect([Bind(Include = "Id")] Subscription subscription)
        {
            if (ModelState.IsValid)
            {
                AzureResourceManagerUtil.GrantRoleToServicePrincipalOnSubscription(ConfigurationManager.AppSettings["ObjectId"], 
                    subscription.Id, ConfigurationManager.AppSettings["AADId"]);
                if (AzureResourceManagerUtil.ServicePrincipalHasReadAccessToSubscription(subscription.Id, ConfigurationManager.AppSettings["AADId"]))
                {
                    subscription.ConnectedBy = (System.Security.Claims.ClaimsPrincipal.Current).FindFirst(ClaimTypes.Name).Value;
                    subscription.ConnectedOn = DateTime.Now;

                    db.Subscriptions.Add(subscription);
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index", "Home");
        }
        public ActionResult Disconnect([Bind(Include = "Id")] Subscription subscription)
        {
            if (ModelState.IsValid)
            {
                AzureResourceManagerUtil.RevokeRoleFromServicePrincipalOnSubscription(ConfigurationManager.AppSettings["ObjectId"], 
                    subscription.Id, ConfigurationManager.AppSettings["AADId"]);

                Subscription s = db.Subscriptions.Find(subscription.Id);
                if (s != null)
                {
                    db.Subscriptions.Remove(s);
                    db.SaveChanges();
                }
                
            }

            return RedirectToAction("Index", "Home");
        }
        public ActionResult RepairAccess([Bind(Include = "Id")] Subscription subscription)
        {
            if (ModelState.IsValid)
            {
                AzureResourceManagerUtil.RevokeRoleFromServicePrincipalOnSubscription(ConfigurationManager.AppSettings["ObjectId"], subscription.Id, ConfigurationManager.AppSettings["AADId"]);
                AzureResourceManagerUtil.GrantRoleToServicePrincipalOnSubscription(ConfigurationManager.AppSettings["ObjectId"], subscription.Id, ConfigurationManager.AppSettings["AADId"]);
            }

            return RedirectToAction("Index", "Home");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CloudSense/CloudStack/Views/Home/Index.cshtml
@model CloudStack.Models.HomeIndexViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>CloudStack</h1>
    <p class="lead">Take control of your Azure cloud with CloudStack.</p>
    @if (!Request.IsAuthenticated)
    {
        <p><a href="@Url.Action("SignIn", "Account")" class="btn btn-primary btn-lg">Sign-in &raquo;</a></p>
    }
</div>
<div class="row">
    @if (Request.IsAuthenticated && Model != null)
    {
    <table class="table table-striped table-condensed table-hover">
        <tr>
            <td>
                <h4>Azure Subscription</h4>
            </td>
            <td>
                <h4>Connected to CloudStack?</h4>
            </td>
        </tr>
        @foreach (KeyValuePair<string, CloudStack.Models.Subscription> entry in Model.UserSubscriptions)
        {
            var subscription = entry.Value as CloudStack.Models.Subscription;
            <tr>
                <td>
                    @subscription.DisplayName
                    <br />
                    &nbsp;&nbsp;<small>Subscription Id: @subscription.Id</small>
                </td>
                <td>
                    @if (subscription.IsConnected)
                {
                        <text>Yes. </text>
                        <br />
                        <small>&nbsp;&nbsp; Connected By: @subscription.ConnectedBy </small>
                        <small>&nbsp; Connected On: @subscription.ConnectedOn.ToShortDateString() </small>
                        if (Model.UserCanManageAccessForSubscriptions.Contains(@subscription.Id))
                        {

                            @Html.ActionLink("Disconnect", "Disconnect", "Subscription", new
                   {
                       Id = @subscription.Id
                   },
                                new { @class = "btn btn-danger btn-xs" })
                        }
                        if (@subscription.AzureAccessNeedsToBeRepaired)
                        {
                            <br />
                            <small>&nbsp;&nbsp; Access in Azure needs to be repaired: </small>
                            @Html.ActionLink("Repair", "RepairAccess", "Subscription", new
                       {
                           Id = @subscription.Id
                       },
                                new { @class = "btn btn-info btn-xs" })
                        }
                    }
                    else
                    {
                        <text>No. </text>
                        if (Model.UserCanManageAccessForSubscriptions.Contains(@subscription.Id))
                        {
                            @Html.ActionLink("Connect", "Connect", "Subscription", new
                   {
                       Id = @subscription.Id
                   },
                                new { @class = "btn btn-success btn-xs" })
                        }
                    }
                    @if (!Model.UserCanManageAccessForSubscriptions.Contains(@subscription.Id))
                {
                        <text>(You can't manage access for this subscription.)</text>
                    }
                </td>
            </tr>
        }
    </table>
    }
</div>