TrainingPoint/TrainingPoint/Models/Training.cs
//----------------------------------------------------------------------------------------------
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//----------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TrainingPoint.Models
{
    public class Training
    {
        [Key]
        public int Id { get; set; }
        public string OrganizationId { get; set; }
        public string CreatedBy { get; set; }
        [NotMapped]
        public string CreatedByDisplay 
        {
            get {
                if (CreatedBy == null) return null;
                else return TrainingPoint.GraphUtil.LookupDisplayNameOfAADObject(CreatedBy);
            }
        }
        public string Name { get; set; }
        public string Description { get; set; }
        public ICollection <AccessControlEntry> SharedWith { get; set; }

        public Training() { SharedWith = new List<AccessControlEntry>(); }
    }
}

TrainingPoint/TrainingPoint/Controllers/TrainingController.cs
//----------------------------------------------------------------------------------------------
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//----------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TrainingPoint;
using TrainingPoint.Models;


namespace TrainingPoint.Controllers
{
    [AuthorizeUser(Roles = "admin, trainer, trainee")]
    public class TrainingController : Controller
    {
        private DataAccess db = new DataAccess();

        // GET: Training
        public async Task<ActionResult> Index()
        {
            //access to training could be granted either directly to the user or to a group that the user is member of. 
            //prepare a single list of objectIds to compare = user's objectId and objectIds of all groups the user is member of.
            List <string> objectIdsToCompare = new List<string>();
            objectIdsToCompare = await GraphUtil.GetMemberGroups(ClaimsPrincipal.Current.Identity as ClaimsIdentity);
            string userObjectId = (ClaimsPrincipal.Current).
                FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
            objectIdsToCompare.Add(userObjectId);

            //determine what trainings have been shared with the user and their groups
            var trainingIds = db.AccessControlEntries.Where(a => objectIdsToCompare.Contains(a.PrincipalId.ToString())).Select(a => a.TrainingId).ToList();
            //display the trainings that the user created and the ones shared with the user
            var trainings = db.Trainings.Where(t => trainingIds.Contains(t.Id) || t.CreatedBy == userObjectId).ToList();

            return View(trainings); 
        }

         // GET: Training/Details/5
        public ActionResult Details(int id)
        {
            Training training = db.Trainings
                .Where(t => t.Id == id)
                .Include(t => t.SharedWith)
                .FirstOrDefault();
            if (training == null)
            {
                return HttpNotFound();
            }

            List<string> groupMembership = new List<string>();
            string userObjectId = (System.Security.Claims.ClaimsPrincipal.Current).
                FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
            foreach (System.Security.Claims.Claim claim in (System.Security.Claims.ClaimsPrincipal.Current).FindAll("groups"))
                groupMembership.Add(claim.Value);

            List<string> sharedWith = training.SharedWith.Select(s => s.PrincipalId.ToString()).ToList();

            if (training.CreatedBy == userObjectId || groupMembership.Intersect(sharedWith).ToList().Count > 0)
                return View(training);
            else
                return new ViewResult { ViewName = "Error", ViewBag = { message = "Unauthorized - this training has not been shared with you." } };
        }

        // GET: Training/Create
        [AuthorizeUser(Roles = "admin, trainer")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Training/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeUser(Roles = "admin, trainer")]
        public ActionResult Create([Bind(Include = "Name,Description")] Training training)
        {
            if (ModelState.IsValid)
            {
                training.CreatedBy = (System.Security.Claims.ClaimsPrincipal.Current).
                    FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
                training.OrganizationId = (System.Security.Claims.ClaimsPrincipal.Current).
                    FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;
         
                db.Trainings.Add(training);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(training);
        }

        // GET: Training/Edit/5
        [AuthorizeUser(Roles = "admin, trainer")]
        public ActionResult Edit(int id)
        {
            Training training = db.Trainings.Find(id);
            if (training == null)
                return HttpNotFound();

            if (training.CreatedBy == (System.Security.Claims.ClaimsPrincipal.Current).
                    FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value)
                return View(training);
            else
                return new ViewResult { ViewName = "Error", ViewBag = { message = "Unauthorized - only creator can edit training." } };
        }

        // POST: Training/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeUser(Roles = "admin, trainer")]
        public ActionResult Edit([Bind(Include = "Id, Name,Description")] Training training)
        {
            if (ModelState.IsValid)
            {
                Training t = db.Trainings.Find(training.Id);
                if (training.CreatedBy == (System.Security.Claims.ClaimsPrincipal.Current).
                        FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value)
                {
                    db.Entry(training).State = EntityState.Modified;
                    db.SaveChanges();
                }
                else
                {
                    return new ViewResult { ViewName = "Error", ViewBag = { message = "Unauthorized - only creator can edit training." } };
                }
            }
            return RedirectToAction("Index");
        }

        // GET: Training/Delete/5
        [AuthorizeUser(Roles = "admin, trainer")]
        public ActionResult Delete(int id)
        {
            Training training = db.Trainings.Find(id);
            
            if (training == null)
                return HttpNotFound();
            
            if (training.CreatedBy == (System.Security.Claims.ClaimsPrincipal.Current).
                        FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value)
                return View(training);
            else
                return new ViewResult { ViewName = "Error", ViewBag = { message = "Unauthorized - only creator can delete training." } };
        }

        // POST: Training/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeUser(Roles = "admin, trainer")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Training training = db.Trainings.Find(id);
            if (training.CreatedBy == (System.Security.Claims.ClaimsPrincipal.Current).
                FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value)
            {
                db.Trainings.Remove(training);
                db.SaveChanges();
            }
            else
                return new ViewResult { ViewName = "Error", ViewBag = { message = "Unauthorized - only creator can delete training." } };
            
            return RedirectToAction("Index");
        }
        [HttpPost]
        [AuthorizeUser(Roles = "admin, trainer")]

        public ActionResult Share(int Id, string UserOrGroupSearchString)
        {
            Training training = db.Trainings
                .Where(t => t.Id == Id)
                .Include(t => t.SharedWith)
                .FirstOrDefault();

            if (training != null)
            {
                if (training.CreatedBy == (System.Security.Claims.ClaimsPrincipal.Current).
                    FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value)
                {
                    string objectIdOfUserOrGroup = GraphUtil.LookupObjectIdOfAADUserOrGroup(UserOrGroupSearchString);
                    if (!string.IsNullOrEmpty(objectIdOfUserOrGroup))
                    {
                        var ace = db.AccessControlEntries.Where(a => a.TrainingId == training.Id && a.PrincipalId == objectIdOfUserOrGroup).FirstOrDefault();
                        if (ace == null)
                        {
                            training.SharedWith.Add(new AccessControlEntry { TrainingId = training.Id, PrincipalId = objectIdOfUserOrGroup });
                            db.SaveChanges();
                        }
                    }
                }
                else
                {
                    return new ViewResult { ViewName = "Error", ViewBag = { message = "Unauthorized - only creator can share training." } };
                }
            }
            return View("Details", training);
        }
        [HttpPost]
        [AuthorizeUser(Roles = "admin, trainer")]
        public ActionResult Unshare(int Id, int trainingId)
        {

TrainingPoint/TrainingPoint/Views/Training/Create.cshtml
@model TrainingPoint.Models.Training

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Training</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TrainingPoint/TrainingPoint/Views/Training/Delete.cshtml
@model TrainingPoint.Models.Training

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Training</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TrainingPoint/TrainingPoint/Views/Training/Details.cshtml
@using TrainingPoint
@using System.Web.Mvc.Html
@model TrainingPoint.Models.Training

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Training</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedByDisplay)
        </dd>
    </dl>
    <hr />
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>


<div>
    <h4>Shared With</h4>
    @using (Html.BeginForm("Share", "Training"))
    {
        @Html.AntiForgeryToken()

        <dl class="dl-horizontal">
            <dt style="width:300px">
                @Html.HiddenFor(model => model.Id)
                <input type="text" class="form-control" name="UserOrGroupSearchString" placeholder="User's email or Security Group's name" />
            </dt>
            <dd>
                <input type="submit" value="Share" class="btn btn-default" />
            </dd>
        </dl>
    }
    @if (Model.SharedWith != null)
    {
        var count = 0;
        foreach (TrainingPoint.Models.AccessControlEntry ace in Model.SharedWith)
        {
            ++count;
            using (Html.BeginForm("Unshare", "Training"))
            {
                <dl class="dl-horizontal" style="align-content:flex-start">
                    <dt style="width:350px;text-align:left">
                        @count. &nbsp; @ace.PrincipalDisplay
                        <input type="hidden" name="Id" value='@ace.Id' />
                        <input type="hidden" name="trainingId" value='@Model.Id'/>
                        <button type="submit" class="btn btn-remove btn-xs">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    </dt>
                    <dd>
                    </dd>
                </dl>
            }
        }
    }
</div>

TrainingPoint/TrainingPoint/Views/Training/Edit.cshtml
@model TrainingPoint.Models.Training

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Training</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TrainingPoint/TrainingPoint/Views/Training/Index.cshtml
@model IEnumerable<TrainingPoint.Models.Training>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedByDisplay)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>