TrainingPoint/TrainingPoint/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrainingPoint.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TrainingPoint/TrainingPoint/Controllers/SignUpController.cs
//----------------------------------------------------------------------------------------------
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//----------------------------------------------------------------------------------------------
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainingPoint.Models;

namespace TrainingPoint.Controllers
{
    public class SignUpController : Controller
    {
        private DataAccess db = new DataAccess();
        public ActionResult SignUp()
        {
            return View();
        }
        // POST: /SignUp/SignUp
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp([Bind(Include = "Id, Name")] Organization organization)
        {
            // generate a random value to identify the request
            string stateMarker = Guid.NewGuid().ToString();
            // store it in the temporary entry for the tenant, we'll use it later to assess if the request was originated from us
            // this is necessary if we want to prevent attackers from provisioning themselves to access our app without having gone through our onboarding process (e.g. payments, etc)
            organization.Issuer = stateMarker;
            organization.CreatedOn = DateTime.Now;
            db.Organizations.Add(organization);
            db.SaveChanges();

            //create an OAuth2 request, using the web app as the client.
            //this will trigger a consent flow that will provision the app in the target tenant

            string signUpReturnUrl = this.Request.Url.GetLeftPart(UriPartial.Path);
            signUpReturnUrl = signUpReturnUrl.Substring(0, signUpReturnUrl.LastIndexOf('/'));
            signUpReturnUrl += "/ProcessCode";

            string authorizationRequest = String.Format(
                "{0}oauth2/authorize?response_type=code&response_mode=form_post&client_id={1}&resource={2}&redirect_uri={3}&state={4}",
                 string.Format(ConfigurationManager.AppSettings["ida:Authority"], "common"),
                 Uri.EscapeDataString(ConfigurationManager.AppSettings["ida:ClientID"]),
                 Uri.EscapeDataString(ConfigurationManager.AppSettings["ida:GraphAPIIdentifier"]),
                 Uri.EscapeDataString(signUpReturnUrl),
                 Uri.EscapeDataString(stateMarker)
                 );
            //some authorization features require administrator consent
            authorizationRequest += String.Format("&prompt={0}", Uri.EscapeDataString("admin_consent"));
            // send the user to consent
            return new RedirectResult(authorizationRequest);
        }

        // POST: /SignUp/ProcessCode
        public ActionResult ProcessCode(string code, string error, string error_description, string resource, string state)
        {
            // Is this a response to a request we generated? Let's see if the state is carrying an ID we previously saved
            // ---if not, return an error            
            if (db.Organizations.FirstOrDefault(a => a.Issuer == state) == null)
            {
                // TODO: prettify
                return View("Error");
            }
            else
            {
                // ---if the response is indeed from a request we generated
                // ------get a token for Graph API, that will provide us with information abut the caller
                ClientCredential credential = new ClientCredential(ConfigurationManager.AppSettings["ida:ClientID"],
                                                                   ConfigurationManager.AppSettings["ida:Password"]);
                AuthenticationContext authContext = new AuthenticationContext(string.Format(ConfigurationManager.AppSettings["ida:Authority"], "common"));
                AuthenticationResult result = authContext.AcquireTokenByAuthorizationCode(
                    code, new Uri(Request.Url.GetLeftPart(UriPartial.Path)), credential);

                var myTenant = db.Organizations.FirstOrDefault(a => a.Issuer == state);
                // if this was an admin consent, save the tenant
                    // ------read the tenantID out of the Graph token and use it to create the issuer string
                    string issuer = String.Format(ConfigurationManager.AppSettings["ida:Issuer"], result.TenantId);
                    myTenant.Issuer = issuer;

                // remove older, unclaimed entries
                DateTime tenMinsAgo = DateTime.Now.Subtract(new TimeSpan(0, 10, 0)); // workaround for Linq to entities
                var garbage = db.Organizations.Where(a => (!a.Issuer.StartsWith("https") && (a.CreatedOn < tenMinsAgo)));
                foreach (Organization o in garbage)
                    db.Organizations.Remove(o);

                db.SaveChanges();
                // ------return a view claiming success, inviting the user to sign in
                return View();
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrainingPoint/TrainingPoint/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TrainingPoint/TrainingPoint/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>TrainingPoint</h1>
    <p class="lead">is a multi-tenant cloud application that uses Azure Active Directory for Authentication as well as Authorization.</p>
    <p>
        <small>
            to try this app with your Azure Active Directory, first @Html.ActionLink("Sign Up", "SignUp", "SignUp"). Then, assign
            users to the TrainingPoint application in the <a href="https://manage.windowsazure.com">Azure Management Portal</a>: Click on the Azure
            Active Directory node, then select your directory, then under the 'Applications' tab select TrainingPoint. If you have Azure AD premium,
            you can assign users as well as well as groups to the TrainingPoint, if not, assign users using the 'Users' tab. While assigning users
            or groups, select the 'Trainer' role to allow them to create and share trainings or select the 'Trainee' role to allow them to only view
            trainings in this application.
        </small>
    </p>
    <p><small>Source code is here: <a href="https://github.com/dushyantgill/VipSwapper">https://github.com/dushyantgill/VipSwapper</a></small></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Single Sign-on with Active Directory and Office 365</h2>
        <p>
            <small>
                TrainingPoint is a multi-tenant web application. To enable customers to sign-in using their on-premises Active Directory accounts
                or their Office 365 accounts, TrainingPoint uses Azure Active Directory as the identity provider.
            </small>
        </p>
        <p><a class="btn btn-default" href="http://msdn.microsoft.com/en-us/library/azure/dn151122.aspx">Learn more about Azure AD multi-tenant apps&raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Application Roles</h2>
        <p>
            <small>

                TrainingPoint uses Azure AD application roles for role-based access control. It declares two application roles: 'Trainer' and 'Trainee'.
                Azure AD Users and Groups are assigned to these roles by the admin and when they sign-in to the application, the 'roles' claim in the token
                contatains the application role(s) that have been assigned to them.
            </small>
        </p>
        <p><a class="btn btn-default" href="http://www.dushyantgill.com/blog/2014/12/10/roles-based-access-control-in-cloud-applications-using-azure-ad/">Learn more about Application Roles &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Groups Claim</h2>

        <p>
            <small>
                TrainingPoint allows users (in the 'Trainer' role) to share the trainings they create with Active Directory groups.
                TrainingPoint uses the Groups Claim feature of Azure AD to determine what AD groups the users is member of, then it allows
                the user to see the trainings that have been shared with those groups.
            </small>
        </p>
        <p><a class="btn btn-default" href="http://www.dushyantgill.com/blog/2014/12/10/authorization-cloud-applications-using-ad-groups/">Learn more about Groups Claim &raquo;</a></p>
    </div>
</div>